services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
